<?php
namespace AppInterFace\Model\ImageSpace;
use AppInterFace\Model\FactoryModel;
use AppInterFace\Model\ImageSpace\ImageSpaceBaseModel;
use AppInterFace\Model\ImageSpace\ImageSpaceInterFaceModel;

class ResultGoodsSlidePicModel extends ImageSpaceBaseModel implements ImageSpaceInterFaceModel{

    private $goodsId;

    private $dbConfig = array();


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->dbConfig['LINE_SLIDE'] = 'trl_line_slide';
        $this->dbConfig['IMAGE_SPACE'] = 'trl_image_space';
    }

    public function response()
    {
        $goodsId = $this->goodsId;
        $config = $this->dbConfig;
        if(empty($goodsId)){
            E('商品id不能为空');
        }
        $where[$config['LINE_SLIDE'].'.gid'] = array('eq',$goodsId);
        $field[] = $config['IMAGE_SPACE'].'.url';
        $ret = $this->table($config['LINE_SLIDE'])->
        join('inner join __IMAGE_SPACE__ ON __LINE_SLIDE__.imageid= __IMAGE_SPACE__.id')->
        where($where)->field($field)->select();
        //如果检索的结果是空的就调用商品表中的图片列表
        if(empty($ret)){
            $this->setObject(FactoryModel::goodsInfo());
            $this->trlData->setGoodsId($goodsId);
            $ret = $this->trlData->response();
            if(empty($ret)){
                echo '不存在商品的图片组！';
                exit;
            }
            return unserialize($ret['slidepic']);
        }
        return $ret;
    }

    /**
     * 设置商品id
    */
    public function setGoodsId($goodsId){
        $this->goodsId = $goodsId;
    }



}